### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by alexkirsz** [botify-labs/react-components#33]
We need to know when a PR breaks the build or doesn't pass every test.

**Comment by jbbarth** [comment]
Like, you issue a PR, Jenkins runs some tests, and leaves a status through the status API on the commit (and the PR btw)? Is this something like what's already in place for our private repositories?

**Comment by jbbarth** [comment]
Btw, _generally_ we use [travis-ci](http://travis-ci.org/) for open-source projects, not the internal jenkins, but YMMV.

**Comment by alexkirsz** [comment]
Yup, that's it.

Travis would need to have NodeJS + npm installed and run `npm run gulp -- lib` and `npm test`.

**Comment by alexkirsz** [comment]
**And**, if it doesn't already for Node projects, it should clean dependencies and reinstall them via `npm install` beforehand.

**Comment by jbbarth** [comment]
OK, then maybe try http://docs.travis-ci.com/user/languages/javascript-with-nodejs/ I think it already has everything needed by default (maybe not `npm run gulb -- lib` but that may be defined in [custom build commands](http://docs.travis-ci.com/user/build-configuration/#Define-custom-build-lifecycle-commands))

**Comment by alexkirsz** [comment]
Nice! I don't have admin rights, can you enable Travis on this repo?

**Comment by jbbarth** [comment]
Sure, I just did! Let me know how it goes and if you need help, but I'm sure you'll be able to make things working with a few trials/errors..

**Comment by alexkirsz** [comment]
Is it supposed to take so long to start, or do I have to flip a switch somewhere? See #34

**Comment by alexkirsz** [comment]
Thanks for the help!
