### ISSUE TITLE
Venn diagram

### ISSUE THREAD

**Issue by zallek** [botify-labs/react-components#8]

**Comment by alexkirsz** [comment]
- [https://github.com/benfred/venn.js](venn.js) uses d3 but does not declare itself as a d3 plugin, very barebones but decently customizable as well, pretty much the only choice
- [https://github.com/habtom/biojs-vis-genvenn](genvenn) more like a web app, uses d3, generates symmetrical venn diagrams from sets of data
- [http://www.cs.uic.edu/~wilkinson/Publications/venneuler.pdf](Exact and Approximate Area-proportional Circular Venn and Euler Diagrams) paper on generating area-proportional venn diagrams

**Comment by alexkirsz** [comment]
Venn Diagram is done.

Currently, the component considers sets to be exclusive (set intersections are substracted from sets) and only works with two sets.

However, the data format handles any number of sets and intersections and is unaware of inclusivity/exclusivity.
